server:
  servlet:
    context-path: /${spring.application.name}
  port: 8079

spring:
  main:
    banner-mode: console
  application:
    name: graphql-spring-boot

  graphql:
    graphiql:
      enabled: true #Enable GraphiQL UI for testing
    schema:
      file-extensions: .graphqls,.gqls #default
      locations: classpath:graphql/**/ #default
    http:
      path: /graphql
    cors:
      allowed-origins: https://example.org
      allowed-methods: GET,POST
      max-age: 1800s

logging:
  level:
    org:
      springframework:
        boot: INFO

management:
  server:
    port: 8070
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: auditevents,beans,caches,conditions,configprops,env,flyway,health,httpexchanges,info,integrationgraph,loggers,liquibase,metrics,mappings,quartz,scheduledtasks,sessions,shutdown,startup,threaddump,heapdump,logfile,prometheus
      path-mapping:
        health: /status