FROM eclipse-temurin:21-jre-jammy AS builder
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=tools -jar application.jar extract --layers --destination app


FROM gcr.io/distroless/java21-debian12
WORKDIR app
COPY --from=packager app/lib/ ./lib/
COPY --from=packager app/application.jar ./

ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

EXPOSE 8080 8070

ENTRYPOINT ["java", "-jar", "/app/application.jar"]