FROM ibm-semeru-runtimes:open-21.0.8_9-jre-noble AS builder
WORKDIR /builder
ARG JAR_FILE=target/g*.jar
COPY ${JAR_FILE} app.jar
RUN java -Djarmode=tools -jar app.jar extract --layers --destination app


FROM ibm-semeru-runtimes:open-21.0.8_9-jre-noble
WORKDIR /app
COPY --from=builder builder/app/dependencies/ ./
COPY --from=builder builder/app/snapshot-dependencies/ ./
COPY --from=builder builder/app/spring-boot-loader/ ./
COPY --from=builder builder/app/application/ ./

ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

EXPOSE 8080 8070

ENTRYPOINT ["java", "-jar", "/app/app.jar"]