FROM alpine/java:21.0.4-jdk AS packager
ARG CUSTOM_JRE=/opt/min_jre
ARG JAR_FILE=target/g*.jar

COPY $JAR_FILE app.jar

RUN /opt/java/openjdk/bin/jlink \
    --module-path /opt/java/openjdk/jmods \
    --verbose \
    --add-modules java.base,java.desktop,java.instrument,java.logging,java.management,java.naming,java.security.jgss,java.sql,java.xml,jdk.unsupported,jdk.management \
    --compress zip-6 \
    --no-header-files \
    --output $CUSTOM_JRE
RUN $CUSTOM_JRE/bin/java -Xshare:dump
RUN mkdir $CUSTOM_JRE/cds
RUN java -Djarmode=tools -jar app.jar extract --destination app
RUN $CUSTOM_JRE/bin/java -XX:ArchiveClassesAtExit=$CUSTOM_JRE/cds/app.jsa -Dspring.context.exit=onRefresh -jar app/app.jar

FROM alpine:3.22.1
ARG CUSTOM_JRE=/opt/min_jre
COPY --from=packager $CUSTOM_JRE $CUSTOM_JRE

ENV JAVA_HOME=$CUSTOM_JRE
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

WORKDIR app
COPY --from=packager app/lib/ ./lib/
COPY --from=packager app/app.jar ./

EXPOSE 8080 8070

ENTRYPOINT ["java", "-Xlog:cds", "-XX:SharedArchiveFile=/opt/min_jre/cds/app.jsa", "-jar", "/app/app.jar"]