FROM alpine/java:21.0.4-jdk AS packager
ARG CUSTOM_JRE=/opt/min_jre
ARG JAR_FILE=target/g*.jar

COPY $JAR_FILE app.jar
RUN java -Djarmode=tools -jar app.jar extract --destination app

RUN jdeps \
    --ignore-missing-deps -quiet \
    --recursive \
    --multi-release 21 \
    --print-module-deps \
    --class-path '/app/lib/*' \
    /app/app.jar > /app/deps.info

RUN jlink \
    --module-path /opt/java/openjdk/jmods \
    --add-modules $(cat /app/deps.info) \
    --strip-debug \
    --compress zip-6 \
    --no-header-files \
    --no-man-pages \
    --output $CUSTOM_JRE

RUN mkdir $CUSTOM_JRE/cds
RUN $CUSTOM_JRE/bin/java -Xshare:dump
RUN $CUSTOM_JRE/bin/java -XX:ArchiveClassesAtExit=$CUSTOM_JRE/cds/app.jsa -Dspring.context.exit=onRefresh -Dspring.profiles.active=appcds,h2 -jar /app/app.jar


FROM alpine:3.22.1 AS runner
COPY --from=packager /opt/min_jre /opt/min_jre

ENV JAVA_HOME=/opt/min_jre
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

COPY --from=packager app/lib/ /app/lib
COPY --from=packager app/app.jar /app

EXPOSE 8080 8070

ENTRYPOINT ["java", "-Xshare:on", "-XX:SharedArchiveFile=/opt/min_jre/cds/app.jsa", "-jar", "/app/app.jar"]
#ENTRYPOINT ["java", "-Xlog:cds", "-Xshare:on", "-XX:SharedArchiveFile=/opt/min_jre/cds/app.jsa", "-jar", "/app/app.jar"]
