FROM eclipse-temurin:24-jre-alpine-3.21 AS packager
ARG JAR_FILE=target/q*.jar

COPY target/*.jar app.jar

RUN java -Djarmode=tools -jar app.jar extract --destination app

WORKDIR /app

RUN java  \
    -XX:AOTMode=record  \
    -XX:AOTConfiguration=app.aotconf  \
    -Dspring.profiles.active=appcds,h2  \
    -Dspring.context.exit=onRefresh  \
    -jar app.jar

RUN java  \
    -XX:AOTMode=create  \
    -XX:AOTConfiguration=app.aotconf  \
    -XX:AOTCache=app.aot  \
    -jar app.jar  \
    && rm app.aotconf

FROM eclipse-temurin:24-jre-alpine-3.21
COPY --from=packager app/lib/ /app/lib
COPY --from=packager app/*.* /app

ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

EXPOSE 8080 8070

WORKDIR /app
#ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-jar", "app.jar"]
ENTRYPOINT ["java", "-Xlog:cds", "-XX:AOTCache=app.aot", "-jar", "app.jar"]