FROM alpine/java:21.0.4-jdk AS packager

ARG JAR_FILE=target/g*.jar
COPY ${JAR_FILE} app.jar
RUN java -Djarmode=tools -jar app.jar extract --destination app

RUN jdeps \
    --ignore-missing-deps -quiet \
    --recursive \
    --multi-release 21 \
    --print-module-deps \
    --class-path '/app/lib/*' \
    /app/app.jar > /app/deps.info

#--add-modules java.base,java.desktop,java.instrument,java.logging,java.management,java.naming,java.security.jgss,java.sql,java.xml,jdk.unsupported,jdk.management \

RUN jlink \
    --module-path /opt/java/openjdk/jmods \
    --add-modules $(cat /app/deps.info) \
    --compress zip-6 \
    --no-header-files \
    --no-man-pages \
    --output /opt/jdk-21-min

ENTRYPOINT ["/opt/jdk-21-min/bin/java", "-jar", "/app/app.jar"]