FROM ibm-semeru-runtimes:open-21.0.8_9-jre-noble
WORKDIR spring
COPY target/graphql*.jar app.jar

ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

EXPOSE 8080 8070

ENTRYPOINT ["java", "-jar", "/spring/app.jar"]
