FROM openjdk:21 AS packager

RUN /usr/java/openjdk-21/bin/jlink \
    --module-path /usr/java/openjdk-21/jmods \
    --verbose \
    --add-modules java.base,java.desktop,java.instrument,java.logging,java.management,java.naming,jdk.unsupported,java.security.jgss,java.sql,java.xml \
    --compress 2 \
    --no-header-files \
    --output /opt/jdk-21-min

FROM openjdk:21
COPY --from=packager /opt/jdk-21-min /opt/jdk-21-min
COPY target/g*.jar /service/app.jar

ENV JAVA_HOME=/opt/jdk-21-min
ENV PATH="$JAVA_HOME/bin:$PATH"

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/service/app.jar"]