FROM alpine/java:21.0.4-jdk AS packager
RUN /opt/java/openjdk/bin/jlink \
    --module-path /opt/java/openjdk/jmods \
    --verbose \
    --add-modules java.base,java.desktop,java.instrument,java.logging,java.management,java.naming,java.security.jgss,java.sql,java.xml,jdk.unsupported,jdk.management \
    --compress zip-6 \
    --no-header-files \
    --output /opt/jdk-21-min
# RUN /opt/jdk-21-min/bin/java -Xshare:dump
RUN mkdir /opt/jdk-21-min/cds

WORKDIR builder
ARG JAR_FILE=target/g*.jar
COPY $JAR_FILE app.jar
RUN /opt/jdk-21-min/bin/java -Djarmode=tools -jar app.jar extract --destination app
RUN /opt/jdk-21-min/bin/java -XX:ArchiveClassesAtExit=/opt/jdk-21-min/cds/app-cds.jsa -Dspring.context.exit=onRefresh -jar app/app.jar

FROM alpine:3.22.1
COPY --from=packager /opt/jdk-21-min /opt/jdk-21-min

ENV JAVA_HOME=/opt/jdk-21-min
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

WORKDIR service
COPY --from=packager builder/app/lib/ ./lib/
COPY --from=packager builder/app/app.jar ./

EXPOSE 8080 8070

ENTRYPOINT ["java", "-XX:SharedArchiveFile=/opt/jdk-21-min/cds/app-cds.jsa", "-jar", "/service/app.jar"]