FROM alpine/java:21.0.4-jdk AS packager
RUN /opt/java/openjdk/bin/jlink \
    --module-path /opt/java/openjdk/jmods \
    --verbose \
    --add-modules java.base,java.desktop,java.instrument,java.logging,java.management,java.naming,java.security.jgss,java.sql,java.xml,jdk.unsupported,jdk.management \
    --compress zip-6 \
    --no-header-files \
    --output /opt/jdk-21-min
RUN /opt/jdk-21-min/bin/java -Xshare:dump
RUN mkdir /opt/jdk-21-min/cds

WORKDIR spring
ARG JAR_FILE=target/g*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract --destination extracted


FROM alpine:3.22.1
COPY --from=packager /opt/jdk-21-min /opt/jdk-21-min

ENV JAVA_HOME=/opt/jdk-21-min
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

WORKDIR spring
COPY --from=packager spring/extracted/dependencies/ ./
COPY --from=packager spring/extracted/snapshot-dependencies/ ./
COPY --from=packager spring/extracted/spring-boot-loader/ ./
COPY --from=packager spring/extracted/application/ ./

EXPOSE 8080 8070

ENTRYPOINT ["java", "-XX:ArchiveClassesAtExit=/opt/jdk-21-min/cds/app-cds.jsa", "org.springframework.boot.loader.launch.JarLauncher"]