FROM alpine/java:21.0.4-jdk AS packager
ARG JAR_FILE=target/g*.jar
COPY ${JAR_FILE} application.jar

RUN /opt/java/openjdk/bin/jlink \
    --module-path /opt/java/openjdk/jmods \
    --verbose \
    --add-modules java.base,java.desktop,java.instrument,java.logging,java.management,java.naming,java.security.jgss,java.sql,java.xml,jdk.unsupported,jdk.management \
    --compress zip-6 \
    --no-header-files \
    --output /opt/jdk-21-min
RUN java -Djarmode=tools -jar application.jar extract --layers --destination extracted


FROM alpine:3.22.1
COPY --from=packager /opt/jdk-21-min /opt/jdk-21-min

ENV JAVA_HOME=/opt/jdk-21-min
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV SERVER_PORT=8080
ENV MANAGEMENT_SERVER_PORT=8070
ENV SERVER_SERVLET_CONTEXT_PATH="/"
ENV	SPRING_PROFILES_ACTIVE=h2

COPY --from=packager extracted/dependencies/ ./
COPY --from=packager extracted/snapshot-dependencies/ ./
COPY --from=packager extracted/spring-boot-loader/ ./
COPY --from=packager extracted/application/ ./

EXPOSE 8080 8070

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]